vich_uploader:
    db_driver: orm

    mappings:
        miniatures:
            # uri_prefix: '%app.path.miniatures%'
            uri_prefix: '/uploads/images/miniatures'
            # upload_destination: '%kernel.project_dir%/public%app.path.miniatures%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/miniatures'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true

        article_images:
            # uri_prefix: '%app.path.article_images%'
            uri_prefix: '/uploads/images/articles'
            # upload_destination: '%kernel.project_dir%/public%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true
